// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehzlipsbkxmywkqxsycy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoemxpcHNia3hteXdrcXhzeWN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyOTY4NzIsImV4cCI6MjA2Mjg3Mjg3Mn0.lPCkm0DFOXHs-MCYjfIBHotwNRb29X69Qk8mw6XVohk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);